version: "3.8"
services:
  db:
    build: .
    container_name: dm_db
    restart: always
    ports:
      - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: admin
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@domain.com
  #     PGADMIN_DEFAULT_PASSWORD: password
